/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_devzhaoyou_gezhaoyou_androidaacencoder_FFAacEncoder */

#ifndef _Included_com_devzhaoyou_gezhaoyou_androidaacencoder_FFAacEncoder
#define _Included_com_devzhaoyou_gezhaoyou_androidaacencoder_FFAacEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_devzhaoyou_gezhaoyou_androidaacencoder_FFAacEncoder
 * Method:    nativeStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_devzhaoyou_gezhaoyou_androidaacencoder_FFAacEncoder_nativeStart
  (JNIEnv *, jobject);

/*
 * Class:     com_devzhaoyou_gezhaoyou_androidaacencoder_FFAacEncoder
 * Method:    nativeSetPcmData
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_devzhaoyou_gezhaoyou_androidaacencoder_FFAacEncoder_nativeSetPcmData
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_devzhaoyou_gezhaoyou_androidaacencoder_FFAacEncoder
 * Method:    nativeStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_devzhaoyou_gezhaoyou_androidaacencoder_FFAacEncoder_nativeStop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
